trigger:
- main

pool:
  name: fep

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          sudo apt-get install python3-venv  -y # If needed
          python3 -m venv .env
          source .env/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install -r ./requirements.txt